windows_docker_builder:    
  timeout_in: 120m
  platform: windows
  os_version: 2019  
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: |
    docker info
    docker build --no-cache -t %CIRRUS_REPO_FULL_NAME%:latest . 
    docker login --username=%DOCKERHUB_USER% --password=%DOCKERHUB_PASS% 
    docker push %CIRRUS_REPO_FULL_NAME%:latest   
    
